#
# Copyright (c) 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Check that the AWX address has been provided
  fail:
    msg: "Variable 'openshift_autoheal_awx_address' is mandatory but it isn't defined"
  when: openshift_autoheal_awx_address is not defined

- name: Check that the AWX password has been provided
  fail:
    msg: "Variable 'openshift_autoheal_awx_password' is mandatory but it isn't defined"
  when: openshift_autoheal_awx_password is not defined

- name: Create a temporary directory for doing work in the target host
  command: mktemp -d -p '' autoheal-XXXXXX
  register: tmpdir
  changed_when: False

- name: Generate the OAuth cookie secret
  command: openssl rand -base64 32
  register: cookie
  changed_when: False

- name: Generate the basic YAML configuration file
  template:
    src: objects.yml.j2
    dest: "{{ tmpdir.stdout }}/objects.yml"
  changed_when: False

- name: Create the list of objects described in the YAML file
  shell: oc apply --filename="{{ tmpdir.stdout }}/objects.yml"

- name: Delete the temporary directory
  file:
    name: "{{ tmpdir.stdout }}"
    state: absent
  changed_when: False
